### ISSUE TITLE
split panics

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/walrus-cli#10]
I got this panic error:
```
panic: runtime error: index out of range [1] with length 1
```

It looks like the usage is not correct and the second parameter is used for two purposes:
https://github.com/lukechampine/walrus-cli/blob/c9a168867b2ef5cf932cc4b0bd5bd99e164b742d/main.go#L473

https://github.com/lukechampine/walrus-cli/blob/c9a168867b2ef5cf932cc4b0bd5bd99e164b742d/main.go#L549

**Comment by lukechampine** [comment]
Oops, good catch. Should be fixed by https://github.com/lukechampine/walrus-cli/commit/c2577a1f011a29800c5679be84621d4c2260b6eb

**Comment by jkawamoto** [comment]
Thanks! This also needs to be updated:

https://github.com/lukechampine/walrus-cli/blob/c2577a1f011a29800c5679be84621d4c2260b6eb/main.go#L80-L86

**Comment by jkawamoto** [comment]
Nevermind, it was correct.
