### ISSUE TITLE
Are split outputs going to the same address?

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/walrus-cli#12]
Does it really split outputs? It looks like all split funds are going to the same output again.

```
Please verify the transaction details:
    28d80dc058e0766110c2c4c2aae67cfcc4bb1fed41e4740e949244adb20c5dcbb13c7d50232f receiving 99 SC
    28d80dc058e0766110c2c4c2aae67cfcc4bb1fed41e4740e949244adb20c5dcbb13c7d50232f receiving 99 SC
    ...
    28d80dc058e0766110c2c4c2aae67cfcc4bb1fed41e4740e949244adb20c5dcbb13c7d50232f receiving 49.99759 SC
```

**Comment by lukechampine** [comment]
An address can control more than one output. For privacy reasons, we usually create a separate address for each output, but in this case I opted to use a single address for all outputs.

**Comment by jkawamoto** [comment]
Understand. Thank you!
