### ISSUE TITLE
Defrag small outputs

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/walrus-cli#14]
It'd be nice if walrus-cli has a command to defrag small outputs command. It would solve this issue: https://github.com/lukechampine/muse/issues/12.

**Comment by lukechampine** [comment]
Added in https://github.com/lukechampine/walrus-cli/commit/861da9d67434e2e0ac6792a8ecf0ad16fc81f0b6

**Comment by jkawamoto** [comment]
Thanks!
