### ISSUE TITLE
defrag's help text is wrong

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/walrus-cli#15]
It shows split's help text:
https://github.com/lukechampine/walrus-cli/blob/861da9d67434e2e0ac6792a8ecf0ad16fc81f0b6/main.go#L242

**Comment by lukechampine** [comment]
Oops. That's what I get for copy-paste 😅

**Comment by lukechampine** [comment]
Fixed in https://github.com/lukechampine/walrus-cli/commit/567c063be02f2c2a2e4eac1cba7d3c0fd0c7b8a6
