### ISSUE TITLE
split fails with "Could not broadcast transaction: transaction set needs more miner fees to be accepted"

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/walrus-cli#16]
Seems fee calculation has a problem.

**Comment by lukechampine** [comment]
Ah, `wallet.DistributeFunds` calculates the fee in terms of the number of inputs, but does not account for the number of outputs. Should be an easy fix.

**Comment by lukechampine** [comment]
Should be fixed by https://github.com/lukechampine/walrus-cli/commit/c79fc6ec584df8ad85720990cc0f7bd6629e6deb

**Comment by jkawamoto** [comment]
Thanks!
