### ISSUE TITLE
wrong number of words in seed phrase

### ISSUE THREAD

**Issue by vargrant** [lukechampine/walrus-cli#8]
I am used 
# ./walrus-cli -a http://127.0.0.1:9999 seed
have answer 12 words

then use in terminal for walrus and in terminal for walrus-cli
# export WALRUS_SEED=<12 words>

and then try to generate address
# ./walrus-cli -a http://127.0.0.1:9999 addr
No index specified; using lowest unused index (0)
Using WALRUS_SEED environment variable
wrong number of words in seed phrase

**Comment by lukechampine** [comment]
Hmm. It's clearly seeing the environment variable. Perhaps an error was introduced when you pasted it.

Can you run `echo $WALRUS_SEED | wc`?

**Comment by vargrant** [comment]
Ok. Sorry my mistake ...
export WALRUS_SEED="must be inside double quotes in other case only first waord will be exported"

Please cose this issue
