### ISSUE TITLE
Transaction logs

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/walrus-cli#9]
It'd be nice if this has a subcommand that prints transaction logs.

**Comment by jkawamoto** [comment]
I haven't known it has `transactions` sub-command:

https://github.com/lukechampine/walrus-cli/blob/de0efa8b555066a520077e484e0a012bf848ffd6/main.go#L90-L93

It'd be better to update the help text:

https://github.com/lukechampine/walrus-cli/blob/de0efa8b555066a520077e484e0a012bf848ffd6/main.go#L40-L47

**Comment by lukechampine** [comment]
Good catch. Fixed in https://github.com/lukechampine/walrus-cli/commit/8414440ec41965177c0b27df083b581081ae603a
